### ISSUE TITLE
Flagging RD cases as high priority

### ISSUE THREAD

**Issue by shesketh** [NHS-NGS/GeL2MDT#135]
Hi,

Would it be possible to flag cases as having a high priority in GeL2MDT, within the RD section of the tool? By default cases would have 'regular' priority, but a flag (which could be used in sorting) for those which are considered high priority would be really helpful.

Thanks,
Sirisha

**Comment by efgstone** [comment]
Hi Sirisha,

GeL2MDT has functionality to flag cases with either URGENT or REANALYSE flags which can be applied to a case under from the proband view - it is called "Case Code" and it can be found under the status section. Would this cover your requirements here?

I don't this this feature is included in the user guide - we need to update this! 

Thanks

Ed

**Comment by efgstone** [comment]
So the assigned case code is visible from the main list of cases and can be ordered from here by clicking the column header. You can also use the search field at the top of the table to search "URGENT" to just display those cases with an URGENT status. Currently the case code is not visible from the assigned cases in a user's profile, but this is something we could look at adding.
