### ISSUE TITLE
Audit panel has incorrect categories listed

### ISSUE THREAD

**Issue by theocole** [NHS-NGS/GeL2MDT#20]
![image](https://user-images.githubusercontent.com/26459532/39860824-9f948612-5436-11e8-8428-e224dea4dd50.png)

Audit panel has the correct number of cases, but for the wrong categories:

![image](https://user-images.githubusercontent.com/26459532/39860868-cb590b42-5436-11e8-9b66-5e0f5cdfdff6.png)

e.g under review here has 133, but audit lists this as the number of validation 
![image](https://user-images.githubusercontent.com/26459532/39860878-d52934c6-5436-11e8-902c-0c4c815999f0.png)

**Comment by pdl30** [comment]
Fixed in commit 94d9e66bfb002bc3b1955be28fa91f6e4c69b961
